#!/bin/bash
set -euo pipefail

main() {
    local book_dir=./book
    local highlightjs_dir=$book_dir/highlight.js
    local theme_dir=$book_dir/src/theme

    echo "Preparing highlight.js submodule"
    git submodule update --init $highlightjs_dir

    (
        cd $highlightjs_dir

        echo "Updating NPM dependencies"
        npm install

        echo "Running highlight.js build script"
        node tools/build.js pikelet pikelet-repl rust bash
    )

    echo "Copying minified sources to the theme directory"
    mkdir -p $theme_dir
    cp $highlightjs_dir/build/highlight.pack.js $theme_dir/highlight.js
}

main
