#!/bin/bash
set -euo pipefail

main() {
    (test -x "$HOME/.cargo/bin/cargo-install-update" || cargo install cargo-update)
    (test -x "$HOME/.cargo/bin/mdbook" || cargo install --vers "^0.1.7" mdbook) # https://github.com/rust-lang-nursery/mdBook#installation
    cargo install-update --all
}

main
