#!/bin/bash
set -euo pipefail

# https://github.com/rust-lang-nursery/mdBook#installation
main() {
    local version="0.1.5"

    if command -v mdbook >/dev/null 2>&1; then
        if [[ $(mdbook --version) == "mdbook v$version" ]]; then
            echo "$(mdbook --version) already installed at $(command -v mdbook)"
        else
            cargo install mdbook --force --vers "=$version"
        fi
    else
        echo "installing mdbook"
        cargo install mdbook --vers "=$version"
    fi
}

main
